[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["Michael Zhou <mhzhou@andrew.cmu.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core", "uagents", "fastapi"]
build-backend = "poetry.core.masonry.api"
